name: Go

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 1-5'

jobs:

  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./comicbot.go

    - name: Run
      run: |
        export WEBHOOK_URL=${{ secrets.WEBHOOK_URL }}
        go run comicbot.go
